waypoints:
  wp0:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  wp_table_1:
    position:
      x: -1.12
      y: 1.20
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.707
      w: 0.707
  wp_table_2:
    position:
      x: 0.80
      y: 1.20
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.707
      w: 0.707
  wp_table_3:
    position:
      x: 1.18
      y: -0.03
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0 
      w: 1.0
  wp_cabinet_1:
    position:
      x: 0.48
      y: -1.24
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.707
      w: 0.707
  wp_cabinet_2:
    position:
      x: -0.4356
      y: -1.24
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.707
      w: 0.707